awardsWeight = {
    "Regional Winners": 0,
    "District Championship Winners": 0,
    "Regional Finalists": 2,
    "District Championship Finalists": 2,
    "Regional Engineering Inspiration Award": 4,
    "Regional Chairman's Award": 5,
    "Rookie All Star Award": 8,
    "District Championship Rookie All Star Award": 8,
    "Wildcard": 9,
    "Waitlist": 10
}

countryWeight = {
    u'Canada': 1,
    u'Brazil': 3,
    u'Czech Republic': 3,
    u'USA': 1,
    u'France': 2,
    u'Ecuador': 4,
    u'Kingdom': 1,
    u'Israel': 2,
    u'Australia': 3,
    u'Singapore': 5,
    u'Germany': 3,
    u'Chile': 4,
    u'Dominican Republic': 4,
    u'Kazakhstan': 5,
    u'Philippines': 5,
    u'Spain': 2,
    u'Netherlands': 2,
    u'Denmark': 2,
    u'Turkey': 4,
    u'Morocco': 5,
    u'Vietnam': 5,
    u'Switzerland': 2,
    u'Poland': 3,
    u'Pakistan': 5,
    u'Mexico': 4,
    u'United Arab Emirates': 5,
    u'India': 5,
    u'United Kingdom': 1,
    u'China': 5,
    u'Colombia': 4,
    u'Japan': 5,
    u'Taiwan': 3,
    u'Bosnia-Herzegovina': 3
}
countryWeight.setdefault(5)
